FROM node:14.16.0-alpine
RUN apk add --no-cache git bash make python

RUN mkdir -p /opt/app
WORKDIR /opt/app

COPY package.json /opt/app
COPY package-lock.json /opt/app
RUN npm install

COPY . /opt/app
CMD ["npm", "run", "dev"]
